package com.renren.greendaodemo.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.renren.greendaodemo.Student;
import com.renren.greendaodemo.StudentOne;

import com.renren.greendaodemo.bean.greendao.StudentDao;
import com.renren.greendaodemo.bean.greendao.StudentOneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig studentOneDaoConfig;

    private final StudentDao studentDao;
    private final StudentOneDao studentOneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        studentOneDaoConfig = daoConfigMap.get(StudentOneDao.class).clone();
        studentOneDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        studentOneDao = new StudentOneDao(studentOneDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(StudentOne.class, studentOneDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        studentOneDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public StudentOneDao getStudentOneDao() {
        return studentOneDao;
    }

}
